'use client';
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import {AuthContextProvider} from './Context/AuthContext';
import {usePathname} from 'next/navigation';
import ProtectedRoute from './ProtectedRoute';
import Navbar from './Navbar';

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const noAuthRequired = ['/','/Login','/Signup'];

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const pathname = usePathname().trim();
  return (
      <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
        <Navbar/>
          {noAuthRequired.includes(pathname)?(children):(
            <ProtectedRoute>
              {children}
            </ProtectedRoute>
          )}
        </AuthContextProvider>
      </body>
    </html>
  )
}
